In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.5 MB 1.3 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/12.5 MB 1.3 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/12.5 MB 1.5 MB/s eta 0:00:08
   ------ --------------------------------- 2.1/12.5 MB 1.7 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.5 MB 1.9 MB/s eta 0:00:06
   ----------- ---------------------------- 3.7/12.5 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.5 MB 2.3 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.5 MB 2.6 MB/s eta 0:00:03
   ------------------- ----

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)


2.4.6


In [ ]:
import numpy as np 

In [4]:
import numpy as np 
arr=np.array ([10,20,30])
print(arr)
print(type(arr))

[10 20 30]
<class 'numpy.ndarray'>


In [8]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [12]:
arr3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
